version: '3.7'

services:
  slimfaas:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: docker.io/axaguildev/slimfaas:latest
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    ports:
      - 5020:5000
    environment:
      - BASE_FUNCTION_URL=http://{function_name}:5000
      - BASE_FUNCTION_POD_URL=http://{function_name}:5000
      - MOCK_KUBERNETES_FUNCTIONS={"Functions":[{"Name":"fibonacci","NumberParallelRequest":1}],"Slimfaas":[{"Name":"slimfaas-1"}]}
      - BASE_SLIMDATA_URL=http://localhost:3262/
      - HOSTNAME=slimfaas-1
      - SLIMDATA_CONFIGURATION={"coldStart":"true"}
      - SLIMFAAS_PORTS=5000,5020
      - SLIMFAAS_SUBSCRIBE_EVENTS=reload=>https://host.docker.internal:5002
  fibonacci:
    #image: docker.io/axaguildev/fibonacci:latest
    build:
      context: src/Fibonacci
      dockerfile: ./Dockerfile
    ports:
      - 5021:5000
    environment:
      - BASE_FUNCTION_URL=http://{function_name}:5000
      - Logging:LogLevel:Default=DEBUG
      - ASPNETCORE_URLS=http://+:5000
