---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dailyclean
  namespace: slimfaas-demo
rules:
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
      - patch
    apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
  - verbs:
      - get
      - create
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - workspace-credentials-secret
  - verbs:
      - get
      - create
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - workspace-preferences-configmap
  - verbs:
      - get
      - watch
      - list
      - patch
      - update
    apiGroups:
      - workspace.devfile.io
    resources:
      - devworkspaces
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - controller.devfile.io
    resources:
      - devworkspaceroutings
  - verbs:
      - get
      - create
      - patch
      - update
      - delete
      - list
      - watch
    apiGroups:
      - workspace.devfile.io
    resources:
      - devworkspacetemplates
  - verbs:
      - get
      - create
      - patch
      - update
      - delete
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dailyclean
  namespace: slimfaas-demo
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dailyclean
  namespace: slimfaas-demo
subjects:
  - kind: ServiceAccount
    name: dailyclean
    namespace: slimfaas-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dailyclean
---