---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slimfaas
spec:
  selector:
    matchLabels:
      app: slimfaas
  template:
    metadata:
      labels:
        app: slimfaas
    spec:
      volumes:
        - name: slimfaas-volume
          emptyDir:
            sizeLimit: 10Mi
      serviceAccountName: slimfaas
      containers:
        - name: slimfaas
          image: axaguildev/slimfaas:latest
          env:
            - name: BASE_FUNCTION_URL
              value: "http://{function_name}.slimfaas-demo.svc.cluster.local:5000"
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: NAMESPACE
              value: "slimfaas-demo"
            - name: MOCK_REDIS
              value: "true"
            - name: SLIMDATA_DIRECTORY
              value: "/database"
            #- name: REDIS_CONNECTION_STRING
            #  value: "redis-ha-haproxy:6379"
          volumeMounts:
            - name: slimfaas-volume
              mountPath: /database
          resources:
            limits:
              memory: "76Mi"
              cpu: "4000m"
            requests:
              memory: "76Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
              name: slimfaas
            - containerPort: 3262
              name: slimdata

---
apiVersion: v1
kind: Service
metadata:
  name: slimfaas
spec:
  selector:
    app: slimfaas
  ports:
    - port: 80
      targetPort: 5000
    - port: 3262
      targetPort: 3262
