apiVersion: v1
kind: Namespace
metadata:
  name: slimfaas-demo
  labels:
    name: slimfaas
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slimfaas
  namespace: slimfaas-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-lister
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: slimfaas-demo
  name: deployment-statefulset-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale", "statefulsets/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slimfaas-namespace-lister
subjects:
  - kind: ServiceAccount
    name: slimfaas
    namespace: slimfaas-demo
roleRef:
  kind: ClusterRole
  name: namespace-lister
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slimfaas-deployment-statefulset-manager
  namespace: slimfaas-demo
subjects:
  - kind: ServiceAccount
    name: slimfaas
    namespace: slimfaas-demo
roleRef:
  kind: Role
  name: deployment-statefulset-manager
  apiGroup: rbac.authorization.k8s.io
