apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slimfaas-full-access
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]
  # Add more rules as needed for other API groups

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slimfaas
  namespace: slimfaas-demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slimfaas-binding
subjects:
  - kind: ServiceAccount
    name: slimfaas
    namespace: slimfaas-demo
roleRef:
  kind: ClusterRole
  name: slimfaas-full-access
  apiGroup: rbac.authorization.k8s.io
