name: Docker Images CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

env:
  PNPM_VERSION: 8.6.11
  NODE_VERSION: 18

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"AxaFrance_SlimFaas" /o:"axaguildev" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.coverage.exclusions="src/Fibonacci/**/*,src/FibonacciReact/**/*,demo/**/*"
          dotnet tool install --global dotnet-coverage
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Run unit tests
        run: |
          dotnet test --collect "Code Coverage;Format=cobertura" --verbosity normal
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: './**/TestResults/**/*.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;MarkdownSummaryGithub'
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: CoverageReport # Artifact name
          path: coveragereport # Directory containing files to upload
  tags:
    needs: unit_tests
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: tag_version
        if: github.ref == 'refs/heads/main'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Add tag to output step for main branch
        id: tag
        run: |
          if [ '${{ github.ref }}' = 'refs/heads/main' ]; then
            echo "new_version=${{ steps.tag_version.outputs.new_version }}" >> $GITHUB_OUTPUT
          else
            echo "new_version=pr-${{ github.event.number }}-${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi

  build_slimfaas:
    needs: tags
    uses: ./.github/workflows/Docker.yml
    with:
      image_name: "axaguildev/slimfaas"
      image_version: "${{ needs.tags.outputs.new_version }}"
      image_build_args: ""
      image_context: "."
      image_file: "./Dockerfile"
      platforms: "linux/amd64,linux/arm64"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build_fibonacci:
    needs: tags
    uses: ./.github/workflows/Docker.yml
    with:
      image_name: "axaguildev/fibonacci"
      image_version: "${{ needs.tags.outputs.new_version }}"
      image_build_args: ""
      image_context: "./src/Fibonacci"
      image_file: "./src/Fibonacci/Dockerfile"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build_fibonacci_webapp:
    needs: tags
    uses: ./.github/workflows/Docker.yml
    with:
      image_name: "axaguildev/fibonacci-webapp"
      image_version: "${{ needs.tags.outputs.new_version }}"
      image_build_args: ""
      image_context: "./src/FibonacciReact"
      image_file: "./src/FibonacciReact/Dockerfile"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build_slimfaas_planet_saver:
    needs: tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - name: pnpm ci
        run: pnpm i --frozen-lockfile
        working-directory: ./src/SlimFaasPlanetSaver
      - name: Git Configuration
        id: gitconfig
        run: |
          git config --global user.email "github-action@bot.com"
          git config --global user.name "GitHub"
      - name: pnpm version ${{ steps.tag.outputs.new_version }}
        if: github.ref == 'refs/heads/main'
        run: |
          pnpm version ${{ steps.tag.outputs.new_version }}
        working-directory: ./src/SlimFaasPlanetSaver
      - id: Publish
        uses: JS-DevTools/npm-publish@v1
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          working-directory: ./src/SlimFaasPlanetSaver
